# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you’re using Swift
# use_frameworks!

target "FirebaseUI" do
  pod 'FirebaseUI', '~> 0.2.0'
end